--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BreathTakinglyBinary/libDynamicMiniGames
branches:
  - master
projects:
  DynamicMiniGames:
    path: ""
    model: virion
    type: library
    libs:
      - src: BreathTakinglyBinary/libDynamicBossBar/libDynamicBossBar
        version: ^0.0.4

...
